apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-deployment
          imagePullPolicy: Always
          image: kurtaga/keydash-frontend:v108
          # env:
          #   - name: REACT_APP_BACKEND_URL
          #     value: "http://generator-service:80/get"
          ports:
            - containerPort: 80
