apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: kurtaga/frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameplay-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameplay
  template:
    metadata:
      labels:
        app: gameplay
    spec:
      containers:
        - image: kurtaga/gameplay:latest
          name: gameplay
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/gameplay?sslmode=require
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: VITE_USERS_API_URL
              value: http://51.12.152.201/users/v1/users/
            - name: VITE_REPORTS_API_URL
              value: http://51.12.152.201/v1/reports/
            - name: VITE_GRAPHQL_REPORTS_API_URL
              value: http://51.12.152.201/v1/graphql
            - name: VITE_GENERATOR_API_URL
              value: http://51.12.152.201/generator/
            - name: VITE_GAMEPLAY_URL
              value: http://20.240.34.248/gameplay/v1/gameplay
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: server
          #   initialDelaySeconds: 20
          #   periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: kurtaga/generator-ms:latest
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/generator?sslmode=require
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: VITE_USERS_API_URL
              value: http://51.12.152.201/users/v1/users/
            - name: VITE_REPORTS_API_URL
              value: http://51.12.152.201/v1/reports/
            - name: VITE_GRAPHQL_REPORTS_API_URL
              value: http://51.12.152.201/v1/graphql
            - name: VITE_GENERATOR_API_URL
              value: http://51.12.152.201/generator/
            - name: VITE_GAMEPLAY_URL
              value: http://20.240.34.248/gameplay/v1/gameplay
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: tmiklavic/users:latest
          name: users
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/users?sslmode=require
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: VITE_USERS_API_URL
              value: http://51.12.152.201/users/v1/users/
            - name: VITE_REPORTS_API_URL
              value: http://51.12.152.201/v1/reports/
            - name: VITE_GRAPHQL_REPORTS_API_URL
              value: http://51.12.152.201/v1/graphql
            - name: VITE_GENERATOR_API_URL
              value: http://51.12.152.201/generator/
            - name: VITE_GAMEPLAY_URL
              value: http://20.240.34.248/gameplay/v1/gameplay
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - name: reports
          image: tmiklavic/reports:latest
          imagePullPolicy: Always
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/reports?sslmode=require
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: VITE_USERS_API_URL
              value: http://51.12.152.201/users/v1/users/
            - name: VITE_REPORTS_API_URL
              value: http://51.12.152.201/v1/reports/
            - name: VITE_GRAPHQL_REPORTS_API_URL
              value: http://51.12.152.201/v1/graphql
            - name: VITE_GENERATOR_API_URL
              value: http://51.12.152.201/generator/
            - name: VITE_GAMEPLAY_URL
              value: http://20.240.34.248/gameplay/v1/gameplay
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
